### ISSUE TITLE
priority queue

### ISSUE THREAD

**Issue by vtolstov** [ef-ds/deque#19]
thanks for this package, but for new project i need queue with priority. Does it possible to build queue with priority using this package?

**Comment by christianrpetrin** [comment]
Hello @vtolstov,

thanks very much for considering using the ef-ds Deque. Unfortunately ef-ds still doesn't have a priority queue implementation yet. We're planning to implement one sometime this year. In the meantime, we found the [cookiejar collection](https://github.com/karalabe/cookiejar/tree/v2) to be of very high quality and would recommend considering using their [priority queue](https://github.com/karalabe/cookiejar/blob/v2/collections/prque/prque.go) implementation. We'll let you know when ef-ds has a priority queue implementation as well.

Closing the issue for now.

**Comment by tsoeiroecore** [comment]
@christianrpetrin hi! Ay updates on the priority queue effort?
